repos:
  - repo: https://github.com/msabramo/FawltyDeps
    rev: 4bca742
    hooks:
      - id: check-undeclared
        args:
          - --detailed
          - --code     # --code always has to be last argument, because it must precede list of files
      - id: check-unused
        args:
          - --detailed
