repos:
  - repo: https://github.com/msabramo/FawltyDeps
    rev: 72512447f81236f981aaee12a6f93a4f7052d7a4
    hooks:
      - id: check-undeclared
        args:
          - --detailed
          - --code     # --code always has to be last argument, because it must precede list of files
